spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 93522138807-c5mir4fqgi7gaa7egg7jqtd56psfek65.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080
