-- Audit log Table
CREATE TABLE AuditLog (
  AuditID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TransactionID NUMBER,
  AccountID NUMBER,
  Amount NUMBER,
  TransactionType VARCHAR2(10),
  LoggedAt DATE DEFAULT SYSDATE
);

-- Creating the Trigger

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
  INSERT INTO AuditLog (TransactionID, AccountID, Amount, TransactionType)
  VALUES (:NEW.TransactionID, :NEW.AccountID, :NEW.Amount, :NEW.TransactionType);
END;
/
